version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: database_develop
    environment:
      POSTGRES_DB: sug_develop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
